from Fabrics.MotorcycleFabric import MotorcycleFabric
from Fabrics.CarFabric import CarFabric
from Fabrics.EScooterFabric import EScooterFabric
from Fabrics.BicycleFabric import BicycleFabric
from Fabrics.ScooterFabric import ScooterFabric